# This file controls the AWS CodeBuild

version: 0.2

phases:
  install:
    runtime-versions:
        java: openjdk8
  build:
    commands:
      - mvn clean
      - mvn install
artifacts:
  files:
    - 'Dockerfile'
    - 'target/aws-demo-deploy-0.0.1-SNAPSHOT.jar'
